### ISSUE TITLE
Requests for 1.1.85-beta

### ISSUE THREAD

**Issue by meceware** [Imperial-lord/INR-miAyarla#110]
+ [x] On the doctor side, add a medicine, complete it. Then click on `Add Medicine` button again. Even if it should be a new medicine, timings and notes seems to be grabbed from the old screen. I think the arrays there need to be refreshed.

+ [x] There is no medicine notifications on the patient side. I've been trying with different scenarios, it was working before, now it's not. (the schedular button is green on the patient side.)

+ [x] The notifications on the patient side, don't work after transfering the patient to a new doctor.

+ [x] Something weird happened. I entered a dosage on the doctor side to 10pm, then 10:03pm, updated, 10:05pm updated, 09:58pm updated, 09:53pm updated. On every update I rescheduled it on the patient side. On 09:58 and 09:53, I didn't get any notifications. On 10pm, I got 5 notifications. Is that normal?

![image](https://user-images.githubusercontent.com/16402717/117870440-cd14b880-b2a4-11eb-8c4c-fbdd9ed0a840.png)

**Comment by Imperial-lord** [comment]
Fixed with #112
