### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by meceware** [Imperial-lord/INR-miAyarla#115]
+ [x] Change default app prefix to +90 instead of +91. `1.1.92-beta`

+ [x] In the main app page, a space is required between "Oturum" and blue "aç". `1.1.92-beta`
![image](https://user-images.githubusercontent.com/16402717/118390347-4448a480-b637-11eb-9a4c-f0e548bc73dc.png)

+ [x] I added my phone number to `Doctors Database` collection. When I select `Doctor` on the sign in page, it says Approved however a blank screen comes afterwards. Do I need to add somewhere else? `1.1.92-beta`

![image](https://user-images.githubusercontent.com/16402717/118390415-a4d7e180-b637-11eb-814c-a3c9433e6ca5.png)
![image](https://user-images.githubusercontent.com/16402717/118390421-a7d2d200-b637-11eb-9c8e-3b5c7e697153.png)

**Comment by Imperial-lord** [comment]
You do not need to add it anywhere else. Sometimes, because of internet issues (very rarely), the app might have problems connecting to Firebase. Just restart the app and it should work fine.

**Comment by Imperial-lord** [comment]
> You do not need to add it anywhere else. Sometimes, because of internet issues (very rarely), the app might have problems connecting to Firebase. Just restart the app and it should work fine.

The issue in this particular case was because a string was being passed as null to a Widget. This happened because of the Turkish Translation. We need to check for more such possible cases before release.
