### ISSUE TITLE
Notes and Updates

### ISSUE THREAD

**Issue by meceware** [Imperial-lord/INR-miAyarla#24]
Hi AB,

I got the app installed on Nox for now, it seems to be working fine. I just have a couple notes:

- Gender can be a select box on the patient setup.

- Please hide the sign up date here, the option will be there but there is no need to show the date to the end-user.

- The text boxes doesn't seem to be respond on enter, which means I can't enter two lines of text. This might be a Nox thing though, not sure. Just wanted to add the note here.

Thanks, looking forward to the new updates.

**Comment by meceware** [comment]
I don't think there is a need for a heading on the home page, written as `Home`.

![image](https://user-images.githubusercontent.com/16402717/110990471-6d715e00-8384-11eb-8e6d-320bfc6fea2c.png)


Doctor details seems to be fine except the address line, if you could add an option for a hospital name and department name for the doctors, we can show it here. As in
```
Dr. Elizabeth Owens
Endocrinology, 
Hospital Name, City (or department)
```

Does this sound good?

**Comment by meceware** [comment]
Could you make the buttons bigger? Some old people will use this app :) Doctors told me the old guys are grumpy when they couldn't tap on the buttons :)

**Comment by Imperial-lord** [comment]
> Could you make the buttons a little bit bigger? Some old people will use this app :) Doctors told me the old guys are grumpy when they couldn't tap on the buttons :)
> 
> Other than these, the interface looks fine.

I'll fix that asap, no worries.

**Comment by Imperial-lord** [comment]
> I don't think there is a need for a heading on the home page, written as `Home`.
> 
> ![image](https://user-images.githubusercontent.com/16402717/110990471-6d715e00-8384-11eb-8e6d-320bfc6fea2c.png)
> 
> Doctor details seems to be fine except the address line, if you could add an option for a hospital name and department name for the doctors, we can show it here. As in
> 
> ```
> Dr. Elizabeth Owens
> Endocrinology, 
> Hospital Name, City (or department)
> ```
> 
> Does this sound good?

For the second part sure. For the first thing, do you want me to remove the **Home** thing? Or should I replace it with something else. Also in the bottom nav bar, I have used **Home**, what should we do about that?

**Comment by Imperial-lord** [comment]
> Hi AB,
> 
> I got the app installed on Nox for now, it seems to be working fine. I just have a couple notes:
> 
>     * Gender can be a select box on the patient setup.
> 
>     * Please hide the sign up date here, the option will be there but there is no need to show the date to the end-user.
> 
>     * The text boxes doesn't seem to be respond on enter, which means I can't enter two lines of text. This might be a Nox thing though, not sure. Just wanted to add the note here.
> 
> 
> Thanks, looking forward to the new updates.

I'll fix the gender and sign-up date thing. About the text-boxes, the user does not need an enter button, the cursor will automatically come to the next line if the current line is done. (Think of most messaging apps we use, the enter key is usually meant for sending, or for showing that the current action (of typing in that text boxes) is complete. Let me know what you think. 😄

**Comment by meceware** [comment]
Thank you for the followup.

> For the first thing, do you want me to remove the Home thing? 
Actually the header brings color to the page, that's for sure. I think we can write the app name or something other than Home there, maybe move the doctor name there. Not sure yet :) I just don't like Home text there.

> A similar thing is also there in the doctors side, where he will see the list of all his patients (sort of a doctor's homepage).
I don't think the doctors need to see their patients on the home page all together, however they will need to follow up on the patients to there should be a list somewhere. A link on the homepage to this page, maybe a patient search bar ?

>  About the text-boxes, the user does not need an enter button, the cursor will automatically come to the next line if the current line is done.
If you think this is how it's done, I'm OK with it.

**Comment by Imperial-lord** [comment]
> > A similar thing is also there in the doctor's side, where he will see the list of all his patients (sort of a doctor's homepage).
> 
> I don't think the doctors need to see their patients on the home page all together, however they will need to follow up on the patients to there should be a list somewhere. A link on the homepage to this page, maybe a patient search bar ?

What do you propose should be on the doctor's home page? Here is what I was planning. 
* The first page could be (sort of home) where he sees a list of all his patients. Tapping on a list item will take him to the page of a patient where he can do all the customization (add medicines, dates), chat, send notif and all.
* The next one would be a view (and edit) profile page. 
* Then we'd have sort of a 'Add More doctors' page and finally an 'About App' page as we have in the Patient's side.
Here is a screenshot of the skeleton view: (the bottom nav will give you an idea):
![WhatsApp Image 2021-03-13 at 11 44 24 AM](https://user-images.githubusercontent.com/45942031/111021367-b4e20380-83f1-11eb-9032-a7d156d16c48.jpeg)

**Comment by Imperial-lord** [comment]
> > For the first thing, do you want me to remove the Home thing?
> 
> Actually the header brings color to the page, that's for sure. I think we can write the app name or something other than Home there, maybe move the doctor name there. Not sure yet :) I just don't like Home text there.

That's a minor fix so let me know if you come across a good idea 💡 . We could maybe put the hospital name there 🤔

**Comment by Imperial-lord** [comment]
The issues over here have either been all resolved or might be referenced in the future.
