### ISSUE TITLE
Patient Signup and Patient Side Issues

### ISSUE THREAD

**Issue by meceware** [Imperial-lord/INR-miAyarla#48]
- [x] On the signup page, `Your Gender` needs to be a select box. (`Male`, `Female`) Other is not necessary here.

- [x] I can't enter a new line on the `Your Residence Address` multiline textbox. For example, I'd like to add 
```
My address line 1
Another address line 2
```
but I need to enter it on a single line somehow. Could it be a multiline textbox?

- [x] The new line issue is happening on `Your ailments`, `Your allergies`, `Your genetic disorders` text box as well.

- [x] The home page looks great by design.

- [x] On the home page, the dates (`Last Visit` and `Next Visit`) need to be seen as `DD/MM/YEAR` instead of `2021-03-16` as in `16/03/2021`. This is valid for all the dates.

- [x] Is there a way to upload Latest Test Results? If not, let's add this as another issue. With this issue:

  - [x] The patient can upload a photo or file (pdf) of test results.
  - [x] The patient or the doctor can open the test results, which has a button for it.

- [x] The issue for the chat screen will be created.

- [x] The issue for the Notifications screen will be created.

- [x] The issue for assigning patient to the doctor will be created.

- [x] Notifications screen looks great by design.

- [x] Notifications: Past notifications looks great. Let's limit the count of past notifications by 10. I don't want the user scroll down all the time. All future notifications will be seen here.

- [x] Notifications: We can remove the text `You will receive push notifications at the appropriate time`. The page looks great with the list as is.

- [x] `Your Profile` page looks great by design.

- [x] Your Profile: Let's remove the Profile text at the top of this screen.

- [x] `Edit Profile` doesn't work right now, the database saving issue will be created.

- [x] `About App`: I asked my friend to write a couple things. I will let you know the text here.

**Comment by meceware** [comment]
- [ ] Please hide `Your sign up date` from the patients.

**Comment by meceware** [comment]
`v0.27` Issues

+ [ ] `your ailments` and other textboxes seem to be multiline but `Your Residence Address` textbox isn't.

+ [ ] The charachter set should be updated with a Turkish compatible one (maybe UTF-8?) because the About App section doesn't seem to show the correct text.

![image](https://user-images.githubusercontent.com/16402717/112751118-f3bcaf80-8fd4-11eb-99ab-295cbb90d956.png)

+ [ ] The `Medical History` alignment will be fixed. The wrap works though.

![image](https://user-images.githubusercontent.com/16402717/112751144-09ca7000-8fd5-11eb-82b4-99a23ac10aa1.png)
![image](https://user-images.githubusercontent.com/16402717/112751223-70e82480-8fd5-11eb-970c-e8a84e56f704.png)

+ [ ] Chat doesn't seem to send notifications to the doctor. If the doctor checks, the message is seen btw. 

+ [ ] In the chat screen, I think a file size should be added. I can upload a 3 MB image but I couldn't find the image on the storage so I'm not sure.

**Comment by Imperial-lord** [comment]
- [ ] In `chat screen` and `avatar uploading` - try and compress the image to a particular size to save space. Reference WhatsApp!
