### ISSUE TITLE
Doctor Signup and Doctor Side Issues

### ISSUE THREAD

**Issue by meceware** [Imperial-lord/INR-miAyarla#49]
- [x] If the user asks to be a doctor and closes the app, the app stucks on the splash screen. It needs to start from the beginning and ask for the mobile phone number.

- [x] All right, so if I'm getting this right, a doctor adds a phone number of another doctor first, then the second doctor can register as a doctor. In this case, let's add a check on the Doctor/Patient select. We don't need this check. If the phone number is given by another doctor, he can be registered as doctor, otherwise the phone can be registered as a patient automatically. Is that sound good?

- [x] The new line issue is happening on `your specialisation`, `Hospital Name` text box.

- [x] The home page list looks good and the search box looks great.

- [x] When a search text is entered and removed, the patient list doesn't seem to refresh.

- [x] The patient list doesn't get all the patients for now. They seem to be hardcoded, since the database only has 2 patients for now.

- [x] Patient profile looks great.

- [x] Monitor Patient Healt screen looks great.

- [x] Monitor Patient Health: None of the items seem to save the new and/or old items to the database. This screen will be completed.

- [x] Monitor Patient Health: `Last Visit Date` and `Next visit date` will show a calendar box. I don't understand the purpose of `Edit` button here. If the date changes, it can save the date automatically, or `Save` button can appear here after edit.

- [x] The issue for the (Doctor side) Notifications screen will be created.

- [x] The issue for the (Doctor side) chat screen will be created.

**Comment by Imperial-lord** [comment]
> Monitor Patient Health: Last Visit Date and Next visit date will show a calendar box. I don't understand the purpose of Edit button here. If the date changes, it can save the date automatically, or Save button can appear here after edit.

The purpose is to prevent accidentally tapping the text fields. I'll add the calendar thing on those boxes. Whenever the doctor wants to change the dates, he'll click on edit, and then text fields get activated. On pressing Save, the fields are again made inactive.

**Comment by Imperial-lord** [comment]
> When a search text is entered and removed, the patient list doesn't seem to refresh.

This was happening due to the use of AnimatedList which had a property of initial list count. In some specific cases, the list didn't get refreshed. Replacing with ListView.builder() resolves the issue.
