### ISSUE TITLE
The Screens Stack Up

### ISSUE THREAD

**Issue by meceware** [Imperial-lord/INR-miAyarla#50]
All opened screens seem to stack up, and this can be seen after sign up and check the pages and press `Back` button on the phone. Can this be solved? 

The expected behavior is, on the home page the screens reset when the tab change, otherwise the screens stack up as the user stays and uses on the same tab.

**Comment by Imperial-lord** [comment]
Could you please elaborate a little more as to where we, in particular, this is happening, so that we can resolve this? I have tried to do it at a couple of places. Not sure, if that covers everything!
