### ISSUE TITLE
Add chat notifications and handle notifications while on screen

### ISSUE THREAD

**Issue by Imperial-lord** [Imperial-lord/INR-miAyarla#66]
Discussion Points 💬 
* Chat doesn't seem to send notifications to the doctor. If the doctor checks, the message is seen btw.
* Hey I had a quick question
Suppose the user is using the app and receives a notification (let's say a text message or a medicine a reminder) should I show it as an alert dialog?
It's not possible to show it as a background notification. I can use a Snackbar or an Alert dialog or something else.. let me know what you think is good from the user point of view
  > Yeah, good. Point. Can we show it as a count box-like WhatsApp?

**Comment by meceware** [comment]
> Chat doesn't seem to send notifications to the doctor. If the doctor checks, the message is seen btw.
Is there a technical reason behind it? Does patients get the notifications?

> It's not possible to show it as a background notification. I can use a Snackbar or an Alert dialog or something else.. let me know what you think is good from the user point of view
Both seem OK. We can go with whichever is easier.

**Comment by Imperial-lord** [comment]
@meceware I actually just rewrote your points from our chat and previous issues, and then linked the PR #67. Everything is working as per requirement and working fine!

**Comment by meceware** [comment]
Great! Thank you,
