### ISSUE TITLE
Requests for 0.0.63.alpha

### ISSUE THREAD

**Issue by meceware** [Imperial-lord/INR-miAyarla#95]
## Patient Side

+ [x] After editing profile, it goes home page instead of the Profile screen which was the last screen. (verified in 1.1.73.beta)

+ [x] Please add a `No` button for the `Logout` popup. (On the `Are You Sure` popup) The default button should be `No`.  (verified in 1.1.73.beta)

+ [x] The notifications seem to work good, however, the notifications should be listed as date desc. Right now the first notification sent is seen first, which should be the last. (verified in 1.1.73.beta)

+ [x] There would also be a good addition to remove the notification and list the last 20 notifications max. If it would take time, we can list the last 10 notifications without the remove button.

+ [x] The red dot on the Chat button when there is an unread message, it would look good on the notifications button as well.

+ [x] It seems every time there is an update on the doctors side, the patient need to reschedule the notifications. The notifications actually work. Is there a way to schedule the notifications only once instead of every update?

## Doctor Side

+ [x] On the `Add a medicine` screen, when an entry is added, it goes back to the first field (medicine name) and since it's a text box, the keyboard opens up every time an entry is created. This is so frustrating.
+ [x] After signing up as a patient, I waited but in the end I had to close and open the app to see the patient. Is it about using Firestore but not using Realtime database? 

+ [x] If you send a message from the doctor to a patient, the patient thumbnail image disappears on the chat screen.

+ [x] The patient seems to have a small red dot on the chat button when there is an unread message. On the doctors side, it's shown on the patient name but can you add it to the chat button when the patient name is tapped?

+ [x] After adding a medicine, click on `Add a medicine` button again, the fields are not cleared for a second time.

## Both

+ [x] Patient changing for the doctors will be added. (verified in 1.1.73.beta)
+ [x] Screens stack up, especially after registration, the back button still goes to the previous screen, all the way up to the first screen.

+ [x] I will need an online session to get the app uploaded to play store via my account in the end. The online session will include how to change and build the app, change the version, upload tutorial. Would that be all right?

**Comment by meceware** [comment]
## Doctors
+ [ ]  Please make it hard for the Doctors to remove other doctors. So each doctor can only remove himself, is a good idea. The doctors cannot delete other doctors.

**Comment by meceware** [comment]
On the patient screen, `Current Medications` doesn't seem to show up.

![image](https://user-images.githubusercontent.com/16402717/116822577-3c452b00-ab88-11eb-9b68-2dd259b60aca.png)

**Comment by meceware** [comment]
+ [ ] I didn't see it but the patient can NOT see the doctors phone number. Can you check it if there is a way to do that?

**Comment by meceware** [comment]
+ [ ] Can the app seen as a link sharing utility on Android devices for chat?

**Comment by Imperial-lord** [comment]
> * [ ]  I didn't see it but the patient can NOT see the doctors phone number. Can you check it if there is a way to do that?

Ya, it's easy enough. I'll add a phone number thing in the homescreen

**Comment by Imperial-lord** [comment]
> On the patient screen, `Current Medications` doesn't seem to show up.
> 
> ![image](https://user-images.githubusercontent.com/16402717/116822577-3c452b00-ab88-11eb-9b68-2dd259b60aca.png)

Could you please tell me which version you have used to test the latest release or the 0.0.63-alpha one?

**Comment by meceware** [comment]
> Ya, it's easy enough. I'll add a phone number thing in the homescreen.

Yeah, I think you misunderstood. Do NOT show the phone number of the doctors to patients :)

**Comment by meceware** [comment]
> Could you please tell me which version you have used to test the latest release or the 0.0.63-alpha one?

0.0.63-alpha, android 7.

**Comment by Imperial-lord** [comment]
> > Ya, it's easy enough. I'll add a phone number thing in the homescreen.
> 
> Yeah, I think you misunderstood. Do NOT show the phone number of the doctors to patients :) So I don't see it right now, but maybe I'm missing something, if you are, please remove.

Ah shoot! Ya completely misunderstood. No I am not revealing it anywhere because I know there can always be a random user who can see all your numbers and misuse in anyway otherwise. I just though you wanted the patients to see it.. my bad!

**Comment by Imperial-lord** [comment]
> > Could you please tell me which version you have used to test the latest release or the 0.0.63-alpha one?
> 
> 0.0.63-alpha, android 7.

Wait but did you not already check the notifications and scheduling of medicine notifications?

**Comment by meceware** [comment]
> Ah shoot! Ya completely misunderstood. No I am not revealing it anywhere because I know there can always be a random user who can see all your numbers and misuse in anyway otherwise. I just thought you wanted the patients to see it.. my bad!

All right then, sounds good now :) Just wanted to double check this.

> Wait but did you not already check the notifications and scheduling of medicine notifications in that version? The last time I saw things were working perfectly for me. 

That's right actually. I checked it yesterday, today I run the app again and it was like this.

**Comment by Imperial-lord** [comment]
> That's right actually. I checked it yesterday, today I run the app again and it was like this.
Actually, this was a bug that popped up when there were multiple patients with medicines for each. I have fixed this one in the new release 😄

**Comment by meceware** [comment]
> You will find it fixed in the latest release 

Awesome! Thanks, I will test it soon.

**Comment by meceware** [comment]
+ [ ] The images on the chat screen seem to be reloading all the time.

**Comment by meceware** [comment]
+ [ ] On the chat screen, a message is received from patient to doctor, however the patient message seems to be staying in the end even if the doctor sends message afterwards.

![image](https://user-images.githubusercontent.com/16402717/116912569-1041ac80-ac51-11eb-9759-ea1129a9f4d7.png)

**Comment by meceware** [comment]
+ [ ] Database has insecure rules warning will be removed.

+ [ ] App version will be added to the about page (maybe a new screen?), as well as license texts.
